### ISSUE TITLE
希望点击chrome上的图标可以直接有划词的开关

### ISSUE THREAD

**Issue by sommettop** [oyyd/youdao-collins-chrome-extension#15]
希望点击chrome上的图标可以直接有划词的开关。
现在切换划词要进入options, 显得有点繁琐。

**Comment by oyyd** [comment]
好意见，thx。

**Comment by oyyd** [comment]
增加了临时的划词翻译开关：
<img width="485" alt="2018-06-21 10 47 51" src="https://user-images.githubusercontent.com/5847587/41699534-e05230a0-7556-11e8-8999-b0f1ec1eb6ef.png">
