### ISSUE TITLE
http://dict.youdao.com/ 网址似乎已经无法访问

### ISSUE THREAD

**Issue by xielingsen** [oyyd/youdao-collins-chrome-extension#16]
双击后弹出方框，但一直转圈无法显示查词结果。
发现 http://dict.youdao.com/ 网址似乎已经无法访问，甚至无法 ping 通。
但是 http://www.youdao.com/ 可以访问。是否可以自行设置查词网址？

**Comment by oyyd** [comment]
http://dict.youdao.com/无法访问应该是网络环境导致的，自行设置查词网址，不同网站的api，页面参数不太一样，没有统一的模式并不太容易做

**Comment by oyyd** [comment]
“自行设置查词网址”不容易实现，应该暂不考虑，因此暂时关闭这个问题。
