### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by wasax9t** [oyyd/youdao-collins-chrome-extension#20]
左键查词窗口，只能使用一次加入生词本按钮
其后图标失效只有扇贝链接，无加号。

**Comment by oyyd** [comment]
对于同一个单词，会在页面的生命周期内缓存其保存纪录，之后就直接显示扇贝的链接了。

原本确实是这么设计的，但现在想想关于扇贝词典相关的功能我一直没有考虑太清楚。
