### ISSUE TITLE
查询界面 Bug

### ISSUE THREAD

**Issue by jiagenlee** [oyyd/youdao-collins-chrome-extension#23]
浏览器版本 67.0.3396.87（正式版本） （64 位）

我选的模式是ctrl+单词查询，但是最近在浏览器中要不就是单词界面跳不出来，否则就是一闪而过。

**Comment by oyyd** [comment]
感谢反馈。你可以先试一下重新保存配置能不能解决你碰到的问题。

<img width="522" alt="2018-06-19 1 06 17" src="https://user-images.githubusercontent.com/5847587/41577820-a6eab076-73c1-11e8-8593-6246dc28b4c6.png">

这应该是根chrome extension有关的问题，具体还需要仔细排查。

**Comment by oyyd** [comment]
你的问题我这里没办法复现，但可能跟1.2.0修复了的一个bug有关系。如果还有问题可能需要更详细的信息来帮助排查。

**Comment by jiagenlee** [comment]
我不用 ctrl+划词 这个模式，直接用双击查词，就好使了。

**Comment by oyyd** [comment]
感谢反馈。
