### ISSUE TITLE
建议增加自动发音功能

### ISSUE THREAD

**Issue by FindHao** [oyyd/youdao-collins-chrome-extension#29]
在划词以后，如果可以播放音频，就自动发音。

**Comment by oyyd** [comment]
划词就跳出popup在不少场景下都有些恼人，因而这个插件添加了类似的功能来关闭popup的跳出。基于这点考虑，我觉得自动发音对不少人来说也是让人心烦的特性，暂时应该不会添加该功能。

如果其他人也有类似需求的话在重开这个issue吧。

**Comment by FindHao** [comment]
可以做成一个选项来开关这个特性。
