### ISSUE TITLE
开关翻译需要刷新页面

### ISSUE THREAD

**Issue by FindHao** [oyyd/youdao-collins-chrome-extension#31]
有时刷新页面会导致在页面编辑的内容丢失。建议仿照有道词典的开关模式。如果关闭，页面不需要刷新。

**Comment by FindHao** [comment]
我的环境Debian 9，Chrome69.
点击右上角小绿点关闭插件以后，当前页面仍旧可以划词翻译。刷新页面以后，“关闭”功能才生效。

**Comment by oyyd** [comment]
了解了，thx。

**Comment by oyyd** [comment]
Released in 1.2.1.
