### ISSUE TITLE
Support for Exception URL

### ISSUE THREAD

**Issue by ImSingee** [oyyd/youdao-collins-chrome-extension#36]
In some website, I don’t want to use this extension for some reasons. But there’re not any way to make some advanced settings.

Now, for all websites, I have four settings. I think it would be better if I can set these options separately. 

For example, If I set a rule for “*.shanbay.com” to “按住(meta/ctrl)键 + 划词时翻译”, then this strategy will be used for all websites whose first-level domain is “shanbay.com”. And for other websites, it will match my global rule.

Thank you for this great Chrome Extension!

**Comment by oyyd** [comment]
Thanks for your detailed description! 

But It's a pretty specific scenario that I guess I won't be able to support. PRs are always welcome :)
