### ISSUE TITLE
Advice: let the cursor focus on input box automatically after ctl+q

### ISSUE THREAD

**Issue by vcinex** [oyyd/youdao-collins-chrome-extension#5]

**Comment by oyyd** [comment]
Does this happen in windows? It's okay in osx.

**Comment by vcinex** [comment]
Under ArchLinux with Chromium  58.0.3029.110 (64-bit), it didn't work. Like [this](http://i.imgur.com/i4qJlfH.gifv).

**Comment by oyyd** [comment]
Thank you. I will try to reproduce this and fix it later.

**Comment by vcinex** [comment]
A pleasure.

**Comment by oyyd** [comment]
Fixed on v1.1.2. Chrome may also update it to the newest version automatically.
