### ISSUE TITLE
Chrome 地址栏点击扩展图标查词，光标不会自动定位

### ISSUE THREAD

**Issue by hyxxsfwy** [oyyd/youdao-collins-chrome-extension#6]
如题所述，一个小问题。
系统 Win7 x64，Chrome 自动更新到 59 了。
点击 Chrome 地址栏手动查词时，光标不会自动定位到输入栏，必须要鼠标点一下，略不方便，作者有空改改吧。
#5

**Comment by oyyd** [comment]
看起来和 #5  是同一个问题，看来只有在osx 的chrome会自定定位到input上。和 #4 一起处理后我会发一版，预计在明天上午。感谢反馈！

**Comment by oyyd** [comment]
Fixed on v1.1.2. Chrome may also update it to the newest version automatically.
